/*
 * Filename: Audio_input.h
 * Created on: Nov 22, 2022
 * Author: Shashank Chandrasekaran
 * Description: This H file contains the function declarations related to ADC0 and TPM1
 * Reference: None
 */

#ifndef AUDIO_INPUT_H_
#define AUDIO_INPUT_H_

#include <stdint.h>

/*
 * Function for initialization of TPM1 for ADC sampling
 * Parameter passed: None
 * Parameters returned: None
 */
void Init_TPM1(void);

/*
 * Function for initialization of ADC0
 * Parameter passed: None
 * Parameters returned: None
 */
void Init_ADC0(void);

/*
 * Function for storing 1024 samples of analog output generated by DAC0
 * Parameter passed: inp_buff: The buffer in which samples need to be stored
 * Parameters returned: None
 */
void ADC0_samples_buffer(uint16_t *inp_buff);

/*
 * Function to print min, max, mean, period and frequency as per input samples
 * Parameter passed: inp_buff: The buffer containing samples obtained by ADC0
 * Parameters returned: None
 */
void ADC0_print_samples(uint16_t *inp_buff);

#endif /* AUDIO_INPUT_H_ */
